//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Description()
        {
            this.Flats = new HashSet<Flats>();
        }
    
        public int Id { get; set; }
        public string Access { get; set; }
        public string Description1 { get; set; }
        public string HouseRules { get; set; }
        public string Interaction { get; set; }
        public string Locale { get; set; }
        public string Name { get; set; }
        public string NeighborhoodOverview { get; set; }
        public string Notes { get; set; }
        public string Space { get; set; }
        public string Summary { get; set; }
        public string Transit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flats> Flats { get; set; }
    }
}
