//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonitorEntities : DbContext
    {
        public MonitorEntities()
            : base("name=MonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Description> Description { get; set; }
        public virtual DbSet<Facilities> Facilities { get; set; }
        public virtual DbSet<Flats> Flats { get; set; }
        public virtual DbSet<FlatStatuses> FlatStatuses { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
    }
}
