//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proxyes
    {
        public System.Guid Id { get; set; }
        public string Url { get; set; }
        public Nullable<int> Port { get; set; }
        public int Status { get; set; }
        public Nullable<int> Ping { get; set; }
        public Nullable<System.DateTime> LastUsageTime { get; set; }
        public Nullable<System.DateTime> LastErrorTime { get; set; }
        public string LastError { get; set; }
        public int UseCount { get; set; }
    }
}
