//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiner.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlatStatuses
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> Price { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<long> FlatId { get; set; }
        public Nullable<int> YearNum { get; set; }
        public Nullable<int> MonthNum { get; set; }
    
        public virtual Flats Flats { get; set; }
    }
}
