//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiner.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MonitorEntities : DbContext
    {
        public MonitorEntities()
            : base("name=MonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Facilities> Facilities { get; set; }
        public virtual DbSet<Flats> Flats { get; set; }
        public virtual DbSet<FlatStatuses> FlatStatuses { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Proxyes> Proxyes { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Description> Description { get; set; }
    
        public virtual ObjectResult<TestProc_Result> TestProc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestProc_Result>("TestProc");
        }
    
        public virtual ObjectResult<TestProc2_Result> TestProc2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestProc2_Result>("TestProc2");
        }
    }
}
