//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiner.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proxyes
    {
        public System.Guid Id { get; set; }
        public string Url { get; set; }
        public Nullable<int> Port { get; set; }
        public int Status { get; set; }
        public Nullable<int> Ping { get; set; }
        public Nullable<System.DateTime> LastUsageTime { get; set; }
        public int UseCount { get; set; }
        public int Successes { get; set; }
        public int Fails { get; set; }
        public int Timeouts { get; set; }
        public int TotalPing { get; set; }
        public Nullable<double> AvgPing { get; set; }
        public Nullable<double> Efficiency { get; set; }
        public int Forbidden403 { get; set; }
        public bool Active { get; set; }
    }
}
